handlers_names = [
    'start',
    'menu',
    'help',
    'cancel',
    'busy',
    'chat.chat',
    'user.info',
    # 'non_context_actions.generate_image',
    # 'non_context_actions.extend_image',
    'non_context_actions.non_context_voice',
    'non_context_actions.non_context_photo',
    'non_context_actions.non_context_video_note',
    'non_context_actions.non_context_text',
    'admin.diagnostics',
]
